\input texinfo @c -*-texinfo-*-
@c %**start of header
@include misc/settings.texinfo
@include misc/copying.texinfo
@c %**end of header

@titlepage
   @title @value{bookletTitle}
   @subtitle A Practical Guide for Cuis
   @* @* @* @*

   @bookQuote
   @author @value{writers}

@iftex
   @page
   @vskip 0pt plus 1filll       
   @insertcopying
@end iftex
@end titlepage

@iftex
@c   @shortcontents
   @contents
@end iftex

@node Top

@bookQuote

@*

A journey in Morph world.

@top @value{bookletTitle}

@ifnottex
  @shortcontents
  @insertcopying
@c  @contents
@end ifnottex

@tex
\global\parskip=0.5em
@end tex

@c=====================================
@c Chapters
@c=====================================
@include chapter-01/contents.texinfo
@c
@include chapter-02/contents.texinfo
@c
@include chapter-03/contents.texinfo
@c
@include chapter-04/contents.texinfo
@c
@include chapter-05/contents.texinfo
@c
@include chapter-06/contents.texinfo
@c
@include chapter-07/contents.texinfo
@c
@c=====================================
@c Apprendices
@c=====================================
@c Copyrighted document used in the booklet
@include misc/copyrights.texinfo
@c List of exercises
@node The Exercises
@appendix The Exercises
@listoffloats Exercise
@c Solutions of exercises
@include chapter-50/contents.texinfo
@c List of examples
@node The Examples
@appendix The Examples
@listoffloats Example
@c List of figures
@node The Figures
@appendix The Figures
@listoffloats Figure
@c The games source code package
@appendix Memory Game v1
@anchor{Memory Game v1}
@smallformat
@verbatiminclude misc/MemoryGameV1-untabbed.pck.st
@end smallformat
@appendix Memory Game v2
@anchor{Memory Game V2}
@smallformat
@verbatiminclude misc/MemoryGameV2-untabbed.pck.st
@end smallformat

@c Indexes
@node Indexes
@appendix Conceptual index
@printindex cp
@c=====================================

@c:END OF THE BOOKLET
@bye
