@node Handle user interaction
@chapter Handle user interaction

@*

This chapter will not cover low-level event handling like
mouse clicks, mouse hovers, and key presses.
Instead, it will cover how to use existing widgets, pluggable morphs, etc.,
and how to set up a model.
Important facets to cover include the update/changes and observer pattern.

@menu
@end menu