@node Solutions to the Exercises
@appendix Solutions to the Exercises

@menu
* Layout Components (Solutions)::
@end menu

@c Layout chapter
@node Layout Components (Solutions)
@unnumberedsec Layout Components (Solutions)

@subheading @ref{alignmentTopDown}
Right after the instantiating the box, add these two lines:
@smallexample
box1 layoutSpec offAxisEdgeWeight: #rowTop.
box3 layoutSpec offAxisEdgeWeight: #rowBottom.
@end smallexample

@smalltalk{box2} is centered by default.

@figure{Top to down,ch50-alignmentTopDown,6}

@subheading @ref{exeSpacerQuarter}
Edit the example as follow:
@smallexample
...
spacer1 layoutSpec proportionalWidth: 1.
...
spacer2 layoutSpec proportionalWidth: 3.
...
@end smallexample
